on:
  push:
    tags:
      - v*
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: build
        run: |
          mkdir /opt/bin
          git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
          cd /opt/rt-n56u/trunk

          # build-in smartdns
          wget -P user/smartdns/ https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/smartdns/Makefile
          wget https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/user/Makefile -O user/Makefile
          sed -i '$a\CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y' configs/templates/NEWIFI3.config

          # With v2ray & tproxy for others
          ./clear_tree
          mkdir user/v2ray
          wget -P user/v2ray/ https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/v2ray/Makefile
          sed -i '/module_smart_load("xt_set", NULL);/amodule_smart_load("xt_TPROXY", NULL);' user/rc/rc.c
          sed -i '$a\CONFIG_FIRMWARE_INCLUDE_V2RAY=y' configs/templates/NEWIFI3.config
          fakeroot ./build_firmware_modify NEWIFI3
          mv /opt/rt-n56u/trunk/images/*.trx /opt/bin/NEWIFI3_v2ray.trx

      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Padavan-NEWIFI3-FULL
          path: /opt/bin/*.trx
